on:
  pull_request:
    paths:
      - tools/**
  push:
    paths:
      - tools/**

name: Assign design reviewers
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assigne design reviewers
        run: gh pr edit ${{ github.ref }} --add-assignee taki-on
