name: Create child issues
on:
  issues:
    types: [labeled]
jobs:
  build:
    name: Create child issues
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create child issues
        env: 
          LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
        if: github.event.label.name == 'make-client'
        run: gh issue create \
            --title '[subtask] ${{ github.event.issue.title }}' \
            --body 'Child task of ${{ github.event.issue.url }}' \
            --label '$LABELS'

          
          
