name: Create child issues
on:
  issues:
    types: [labeled]

jobs:
  build:
    name: Create child issues in the client repos
    if: github.event.label.name == 'make-client'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TITLE: '[subtask] ${{ github.event.issue.title }}'
      BODY: 'Child task of ${{ github.event.issue.url }}'
      LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Android child issue
        run: gh issue create --repo 'taki-on/testbed' --title "$TITLE" --body "$BODY" --label "$FINAL_LABELS" | xargs -I % echo "CHILD_ISSUE_URL_ANDROID=%" >> $GITHUB_ENV
      - name: Wait
      - uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Create iOS child issue
        run: gh issue create --repo 'taki-on/testbed' --title "$TITLE" --body "$BODY" --label "$FINAL_LABELS" | xargs -I % echo "CHILD_ISSUE_URL_IOS=%" >> $GITHUB_ENV
      - name: Update the parent issue
        run: gh issue edit ${{ github.event.issue.number }} --body "${{ github.event.issue.body }}\n\n- [ ] $CHILD_ISSUE_URL_ANDROID\n\n- [ ] $CHILD_ISSUE_URL_IOS\n"
        
