name: Create child issues
on:
  issues:
    types: [labeled]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TITLE: '[subtask] ${{ github.event.issue.title }}'
  BODY: 'Child task of ${{ github.event.issue.url }}'
  LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
  LABEL_ALLOW_LIST: 'bug,Severity: 1,Severity: 2,Severity: 3'
permissions:
  issues: write

jobs:
  client_repos:
    name: Create child issues in the client repos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Filter white-listed labels
        run: python3 tools/filter_labels "$LABELS" "$LABEL_ALLOW_LIST" | xargs -I % echo "FINAL_LABELS=%" >> $GITHUB_ENV
      - name: Create Android child issue
        if: github.event.label.name == 'make-client'
        run: gh issue create --repo 'taki-on/testbed' --title "$TITLE" --body "$BODY" --label "$FINAL_LABELS" | xargs -I % echo "CHILD_ISSUE_URL_ANDROID=%" >> $GITHUB_ENV
      - name: Create iOS child issue
        if: github.event.label.name == 'make-client'
        run: gh issue create --repo 'taki-on/testbed' --title "$TITLE" --body "$BODY" --label "$FINAL_LABELS" | xargs -I % echo "CHILD_ISSUE_URL_IOS=%" >> $GITHUB_ENV
      - name: Update the parent issue
        if: github.event.label.name == 'make-client'
        run: |
          NEWLINE=$'\n'
          gh issue edit ${{ github.event.issue.number }} --remove-label "make-client" --body "${{ github.event.issue.body }}${NEWLINE}${NEWLINE}<hr />${NEWLINE}${NEWLINE}#### Generated child issues${NEWLINE}${NEWLINE}<!-- DO NOT MODIFY: Begin auto-managed issue checklist -->${NEWLINE}- [ ] $CHILD_ISSUE_URL_ANDROID${NEWLINE}- [ ] $CHILD_ISSUE_URL_IOS"
  api_repo:
    name: Create child issue in the api repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Filter white-listed labels
        run: python3 tools/filter_labels "$LABELS" "$LABEL_ALLOW_LIST" | xargs -I % echo "FINAL_LABELS=%" >> $GITHUB_ENV
      - name: Create a child issue
        if: github.event.label.name == 'make-api'
        run: gh issue create --repo 'taki-on/testbed' --title "$TITLE" --body "$BODY" --label "$FINAL_LABELS" | xargs -I % echo "CHILD_ISSUE_URL=%" >> $GITHUB_ENV
      - name: Update the parent issue
        if: github.event.label.name == 'make-api'
        run: |
          NEWLINE=$'\n'
          gh issue edit ${{ github.event.issue.number }} --remove-label "make-api" --body "${{ github.event.issue.body }}${NEWLINE}${NEWLINE}<hr />${NEWLINE}${NEWLINE}#### Generated child issues${NEWLINE}${NEWLINE}<!-- DO NOT MODIFY: Begin auto-managed issue checklist -->${NEWLINE}- [ ] $CHILD_ISSUE_URL"
