name: Create child issues
on:
  issues:
    types: [labeled]
jobs:
  build:
    name: Create child issues
    runs-on: ubuntu-latest
    steps:
      - name: Create child issues
        if: github.event.label.name == 'make-client'
        run: |
          echo "${{ github.event.issue.title }}"
          echo "${{ github.event.issue.body }}"
          echo "${{ github.event.issue.url }}"
          echo "${{ join(github.event.issue.labels.*.name, ',') }}"
          gh issue create --title '[subtask] ${{ github.event.issue.title }}' --body 'Child task of ${{ github.event.issue.url }}' --labels '${{ join(github.event.issue.labels.*.name, ',') }}'
          
          
